### PR TITLE
Optimize escaping and unescaping strings

### PR DESCRIPTION
**Pull request by shahar99s**

### CODE REVIEW

**Comment by fda77** [comment]
why do you think this is better?

**Comment by shahar99s** [comment]
It reduces usage of magics and duplicated linea of code, thus reducing the binary size

**Comment by fda77** [comment]
But it is less readable now...

**Comment by wbx-github** [comment]
Please subscribe to our mailinglist and sent a git format-patch -s. This here is just a read-only mirror.

**Pull request closed without merging**
